routes/web.php
<?php

use App\Http\Controllers\AffiliateController;
use App\Http\Controllers\AffiliatePayoutController;
use App\Http\Controllers\APIController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\CampaignController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DatabaseBackupController;
use App\Http\Controllers\DebugController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\OTPApplicationController;
use App\Http\Controllers\OTPController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\PackageSubscriptionController;
use App\Http\Controllers\SenderIDController;
use App\Http\Controllers\TopUpController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SMSController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PermissionGroupController;
use App\Http\Controllers\PaymentResponseController;
use App\Http\Controllers\BusinessSectionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('/shop', [HomeController::class, 'shop'])->name('shop');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');

Route::get('/product/{product}/view', [HomeController::class, 'product'])->name('product');

Auth::routes();
Route::get('/debug', [DebugController::class, 'index'])->name('debug');
Route::group(['middleware' => ['auth']], function () {

    Route::resource('roles', RoleController::class)->middleware('role_or_permission:Super Admin');
    Route::get('roles/data/table', [RoleController::class, 'datatable'])->middleware('role_or_permission:Super Admin');

    Route::resource('permission-groups', PermissionGroupController::class)->middleware('role_or_permission:Super Admin');
    Route::get('permission-groups/data/table', [PermissionGroupController::class, 'datatable'])->middleware('role_or_permission:Super Admin');

    Route::resource('permissions', PermissionController::class)->middleware('role_or_permission:Super Admin');
    Route::get('permissions/data/table', [PermissionController::class, 'datatable'])->middleware('role_or_permission:Super Admin');

    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard')->middleware('role_or_permission:Super Admin|Admin|Businessman|User');

    Route::resource('categories', CategoryController::class);
    Route::get('categories/data/table', [CategoryController::class, 'datatable']);

    Route::resource('brands', BrandController::class);
    Route::get('brands/data/table', [BrandController::class, 'datatable']);

    Route::resource('products', ItemController::class);
    Route::get('products/data/table', [ItemController::class, 'datatable']);

    Route::resource('users', UserController::class);
    Route::get('users/data/table', [UserController::class, 'datatable']);
    Route::patch('users-admin/{user}', [UserController::class, 'updateByAdmin']);
    Route::get('users/profile/{user}', [UserController::class, 'profile'])->name('user.profile');
    Route::patch('users/profile/{user}/update-password', [UserController::class, 'updatePassword'])->name('update.password');
    Route::get('dropdownlist/business-section/{id}',[UserController::class, 'getBusinessSection']);

    Route::resource('sms', SMSController::class)->middleware('role_or_permission:Super Admin|instant SMS index|instant SMS create');
    Route::get('sms/list/view', [SMSController::class, 'listView'])->name('sms.list')->middleware('role_or_permission:Super Admin|instant SMS index|instant SMS create');
    Route::get('sms/data/table', [SMSController::class, 'datatable'])->name('sms.data')->middleware('role_or_permission:Super Admin|instant SMS index|instant SMS create');
    Route::get('api/sms/view', [SMSController::class, 'apiDatatableView'])->name('api.data')->middleware('role_or_permission:Super Admin|api SMS index');
    Route::get('api/data/table', [SMSController::class, 'apiDatatable'])->name('api.list')->middleware('role_or_permission:Super Admin|api SMS index');

    Route::resource('sms-campaigns', CampaignController::class)->middleware('role_or_permission:Super Admin|campaign SMS index|campaign SMS create');
    Route::get('sms-campaigns/list/view', [CampaignController::class, 'listView'])->name('sms-campaigns.list')->middleware('role_or_permission:Super Admin|campaign SMS index|campaign SMS create');
    Route::get('sms-campaigns/data/table', [CampaignController::class, 'datatable'])->name('sms-campaigns.data')->middleware('role_or_permission:Super Admin|campaign SMS index|campaign SMS create');
    Route::get('sms-campaigns-numbers/data/table/{campaignId}', [CampaignController::class, 'datatable_numbers'])->name('sms-campaigns.numbers')->middleware('role_or_permission:Super Admin|sender-id create');

    Route::resource('database-backup', DatabaseBackupController::class)->middleware('role_or_permission:Super Admin|Admin');
    Route::get('database-backup/data/table', [DatabaseBackupController::class, 'datatable'])->middleware('role_or_permission:Super Admin|Admin');
    Route::get('database-backup/download/file/{id}', [DatabaseBackupController::class, 'downloadFile'])->name('db.download')->middleware('role_or_permission:Super Admin|Admin');

});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/about.blade.php
@extends('layouts.front')

@section('content')
    <div class="ht__bradcaump__area bg-image--68">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="bradcaump__inner text-center">
                        <h2 class="bradcaump-title">About us</h2>
                        <nav class="bradcaump-content">
                            <a class="breadcrumb_item" href="index.html">Home</a>
                            <span class="brd-separetor">/</span>
                            <span class="breadcrumb_item active">About us</span>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="page-about about_area bg--white section-padding--lg">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-12 col-12">
                    <div class="thumb">
                        <img src="images/about/big-img/1.jpg" alt="abou images">
                    </div>
                </div>
                <div class="col-lg-6 col-sm-12 col-12">
                    <div class="content">
                        <h3>Wenro Theme</h3>
                        <h2>Fashion Design</h2>
                        <p>Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>
                        <strong>London Address</strong>
                        <p>34 Parer Place via Musk Avenue Kelvin Grove, QLD, 4059</p>
                    </div>
                </div>
            </div>
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-12 col-12">
                    <div class="content text-left text_style--2">
                        <h2>we have skills to show</h2>
                        <div class="skill-container">
                            <!-- Start single skill -->
                            <div class="single-skill">
                                <p>Development</p>
                                <div class="progress">
                                    <div class="progress-bar wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay=".5s" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%"><span class="pen-lable"></span>
                                    </div>
                                </div>
                            </div>
                            <!-- End single skill -->
                            <!-- Start single skill -->
                            <div class="single-skill">
                                <p>Design</p>
                                <div class="progress">
                                    <div class="progress-bar wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay=".5s" role="progressbar" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100" style="width:95%"><span class="pen-lable"></span>
                                    </div>
                                </div>
                            </div>
                            <!-- End single skill -->
                            <!-- Start single skill -->
                            <div class="single-skill">
                                <p>Marketing</p>
                                <div class="progress">
                                    <div class="progress-bar wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay=".5s" role="progressbar" aria-valuenow="93" aria-valuemin="0" aria-valuemax="100" style="width:93%"><span class="pen-lable"></span>
                                    </div>
                                </div>
                            </div>
                            <!-- End single skill -->
                            <!-- Start single skill -->
                            <div class="single-skill">
                                <p>Development</p>
                                <div class="progress">
                                    <div class="progress-bar wow fadeInLeft" data-wow-duration="0.8s" data-wow-delay=".5s" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%"><span class="pen-lable"></span>
                                    </div>
                                </div>
                            </div>
                            <!-- End single skill -->
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-12 col-12">
                    <div class="thumb">
                        <img src="images/about/big-img/2.jpg" alt="abou images">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="wn__team__area pb--130 bg--white">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section__title--3 text-center">
                        <h2>Meet our team of experts</h2>
                        <p>the right people for your project</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <!-- Start Single Team -->
                <div class="col-lg-2 col-md-3 col-sm-6 col-12">
                    <div class="wn__team">
                        <div class="thumb">
                            <img src="images/about/team/1.jpg" alt="Team images">
                        </div>
                        <div class="content">
                            <h4>JOHN SMITH</h4>
                            <p>Designer</p>
                            <ul class="team__social__net">
                                <li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-tumblr icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-linkedin icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Team -->
                <!-- Start Single Team -->
                <div class="col-lg-2 col-md-3 col-sm-6 col-12">
                    <div class="wn__team">
                        <div class="thumb">
                            <img src="images/about/team/2.jpg" alt="Team images">
                        </div>
                        <div class="content">
                            <h4>ALICE KIM</h4>
                            <p>Co-Founder</p>
                            <ul class="team__social__net">
                                <li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-tumblr icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-linkedin icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Team -->
                <!-- Start Single Team -->
                <div class="col-lg-2 col-md-3 col-sm-6 col-12">
                    <div class="wn__team">
                        <div class="thumb">
                            <img src="images/about/team/3.jpg" alt="Team images">
                        </div>
                        <div class="content">
                            <h4>VICTORIA DOE</h4>
                            <p>Marketer</p>
                            <ul class="team__social__net">
                                <li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-tumblr icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-linkedin icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Team -->
                <!-- Start Single Team -->
                <div class="col-lg-2 col-md-3 col-sm-6 col-12">
                    <div class="wn__team">
                        <div class="thumb">
                            <img src="images/about/team/4.jpg" alt="Team images">
                        </div>
                        <div class="content">
                            <h4>JOHN SMITH</h4>
                            <p>Designer</p>
                            <ul class="team__social__net">
                                <li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-tumblr icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-linkedin icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Team -->
                <!-- Start Single Team -->
                <div class="col-lg-2 col-md-3 col-sm-6 col-12">
                    <div class="wn__team">
                        <div class="thumb">
                            <img src="images/about/team/5.jpg" alt="Team images">
                        </div>
                        <div class="content">
                            <h4>ALICE KIM</h4>
                            <p>Co-Founder</p>
                            <ul class="team__social__net">
                                <li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-tumblr icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-linkedin icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Team -->
                <!-- Start Single Team -->
                <div class="col-lg-2 col-md-3 col-sm-6 col-12">
                    <div class="wn__team">
                        <div class="thumb">
                            <img src="images/about/team/6.jpg" alt="Team images">
                        </div>
                        <div class="content">
                            <h4>JOHN SMITH</h4>
                            <p>Designer</p>
                            <ul class="team__social__net">
                                <li><a href="#"><i class="icon-social-twitter icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-tumblr icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-facebook icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-linkedin icons"></i></a></li>
                                <li><a href="#"><i class="icon-social-pinterest icons"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Team -->
            </div>
        </div>
    </section>

@endsection

@push('styles')

@endpush
@push('scripts')

@endpush

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/navigation-dropdown.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-jet-application-mark class="block h-9 w-auto" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-jet-nav-link>
                    <div class="hidden sm:flex sm:items-center sm:ml-6">
                        <x-jet-dropdown align="right" width="48">
                            <x-slot name="trigger">
                                    <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                                        <div>Configurations</div>

                                        <div class="ml-1">
                                            <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                                <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                            </svg>
                                        </div>
                                    </button>
                            </x-slot>

                            <x-slot name="content">
                                <!-- Account Management -->
                                <div class="block px-4 py-2 text-xs text-gray-400">
                                    {{ __('Main Configurations') }}
                                </div>

                                <x-jet-dropdown-link href="{{ route('languages.index') }}">
                                    {{ __('Languages') }}
                                </x-jet-dropdown-link>

                                <div class="border-t border-gray-100"></div>
                                <x-jet-dropdown-link href="{{ route('categories.index') }}">
                                    {{ __('Categories') }}
                                </x-jet-dropdown-link>

                            </x-slot>
                        </x-jet-dropdown>
                    </div>
                    <x-jet-nav-link href="{{ route('posts.index') }}" :active="request()->routeIs('posts')">
                        {{ __('Posts') }}
                    </x-jet-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-jet-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                            <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out">
                                <img class="h-8 w-8 rounded-full object-cover" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                            </button>
                        @else
                            <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                                <div>{{ Auth::user()->name }}</div>

                                <div class="ml-1">
                                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                    </svg>
                                </div>
                            </button>
                        @endif
                    </x-slot>

                    <x-slot name="content">
                        <!-- Account Management -->
                        <div class="block px-4 py-2 text-xs text-gray-400">
                            {{ __('Manage Account') }}
                        </div>

                        <x-jet-dropdown-link href="{{ route('profile.show') }}">
                            {{ __('Profile') }}
                        </x-jet-dropdown-link>

                        @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                            <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                {{ __('API Tokens') }}
                            </x-jet-dropdown-link>
                        @endif

                        <div class="border-t border-gray-100"></div>

                        <!-- Team Management -->
                        @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Manage Team') }}
                            </div>

                            <!-- Team Settings -->
                            <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                {{ __('Team Settings') }}
                            </x-jet-dropdown-link>

                            @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                    {{ __('Create New Team') }}
                                </x-jet-dropdown-link>
                            @endcan

                            <div class="border-t border-gray-100"></div>

                            <!-- Team Switcher -->
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Switch Teams') }}
                            </div>

                            @foreach (Auth::user()->allTeams() as $team)
                                <x-jet-switchable-team :team="$team" />
                            @endforeach

                            <div class="border-t border-gray-100"></div>
                        @endif

                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-jet-dropdown-link href="{{ route('logout') }}"
                                                onclick="event.preventDefault();
                                                            this.closest('form').submit();">
                                {{ __('Logout') }}
                            </x-jet-dropdown-link>
                        </form>
                    </x-slot>
                </x-jet-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-jet-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <img class="h-10 w-10 rounded-full" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                        {{ __('Logout') }}
                    </x-jet-responsive-nav-link>
                </form>

                <!-- Team Management -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="border-t border-gray-200"></div>

                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Manage Team') }}
                    </div>

                    <!-- Team Settings -->
                    <x-jet-responsive-nav-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}" :active="request()->routeIs('teams.show')">
                        {{ __('Team Settings') }}
                    </x-jet-responsive-nav-link>

                    <x-jet-responsive-nav-link href="{{ route('teams.create') }}" :active="request()->routeIs('teams.create')">
                        {{ __('Create New Team') }}
                    </x-jet-responsive-nav-link>

                    <div class="border-t border-gray-200"></div>

                    <!-- Team Switcher -->
                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Switch Teams') }}
                    </div>

                    @foreach (Auth::user()->allTeams() as $team)
                        <x-jet-switchable-team :team="$team" component="jet-responsive-nav-link" />
                    @endforeach
                @endif
            </div>
        </div>
    </div>
</nav>