routes/web.php
<?php

use App\Http\Controllers\AffiliateController;
use App\Http\Controllers\AffiliatePayoutController;
use App\Http\Controllers\APIController;
use App\Http\Controllers\BrandController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\CampaignController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DatabaseBackupController;
use App\Http\Controllers\DebugController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\OTPApplicationController;
use App\Http\Controllers\OTPController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\PackageSubscriptionController;
use App\Http\Controllers\SenderIDController;
use App\Http\Controllers\TopUpController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\SMSController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\PermissionGroupController;
use App\Http\Controllers\PaymentResponseController;
use App\Http\Controllers\BusinessSectionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('/shop', [HomeController::class, 'shop'])->name('shop');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');

Route::get('/product/{product}/view', [HomeController::class, 'product'])->name('product');

Auth::routes();
Route::get('/debug', [DebugController::class, 'index'])->name('debug');
Route::group(['middleware' => ['auth']], function () {

    Route::resource('roles', RoleController::class)->middleware('role_or_permission:Super Admin');
    Route::get('roles/data/table', [RoleController::class, 'datatable'])->middleware('role_or_permission:Super Admin');

    Route::resource('permission-groups', PermissionGroupController::class)->middleware('role_or_permission:Super Admin');
    Route::get('permission-groups/data/table', [PermissionGroupController::class, 'datatable'])->middleware('role_or_permission:Super Admin');

    Route::resource('permissions', PermissionController::class)->middleware('role_or_permission:Super Admin');
    Route::get('permissions/data/table', [PermissionController::class, 'datatable'])->middleware('role_or_permission:Super Admin');

    Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard')->middleware('role_or_permission:Super Admin|Admin|Businessman|User');

    Route::resource('categories', CategoryController::class);
    Route::get('categories/data/table', [CategoryController::class, 'datatable']);

    Route::resource('brands', BrandController::class);
    Route::get('brands/data/table', [BrandController::class, 'datatable']);

    Route::resource('products', ItemController::class);
    Route::get('products/data/table', [ItemController::class, 'datatable']);

    Route::resource('users', UserController::class);
    Route::get('users/data/table', [UserController::class, 'datatable']);
    Route::patch('users-admin/{user}', [UserController::class, 'updateByAdmin']);
    Route::get('users/profile/{user}', [UserController::class, 'profile'])->name('user.profile');
    Route::patch('users/profile/{user}/update-password', [UserController::class, 'updatePassword'])->name('update.password');
    Route::get('dropdownlist/business-section/{id}',[UserController::class, 'getBusinessSection']);

    Route::resource('sms', SMSController::class)->middleware('role_or_permission:Super Admin|instant SMS index|instant SMS create');
    Route::get('sms/list/view', [SMSController::class, 'listView'])->name('sms.list')->middleware('role_or_permission:Super Admin|instant SMS index|instant SMS create');
    Route::get('sms/data/table', [SMSController::class, 'datatable'])->name('sms.data')->middleware('role_or_permission:Super Admin|instant SMS index|instant SMS create');
    Route::get('api/sms/view', [SMSController::class, 'apiDatatableView'])->name('api.data')->middleware('role_or_permission:Super Admin|api SMS index');
    Route::get('api/data/table', [SMSController::class, 'apiDatatable'])->name('api.list')->middleware('role_or_permission:Super Admin|api SMS index');

    Route::resource('sms-campaigns', CampaignController::class)->middleware('role_or_permission:Super Admin|campaign SMS index|campaign SMS create');
    Route::get('sms-campaigns/list/view', [CampaignController::class, 'listView'])->name('sms-campaigns.list')->middleware('role_or_permission:Super Admin|campaign SMS index|campaign SMS create');
    Route::get('sms-campaigns/data/table', [CampaignController::class, 'datatable'])->name('sms-campaigns.data')->middleware('role_or_permission:Super Admin|campaign SMS index|campaign SMS create');
    Route::get('sms-campaigns-numbers/data/table/{campaignId}', [CampaignController::class, 'datatable_numbers'])->name('sms-campaigns.numbers')->middleware('role_or_permission:Super Admin|sender-id create');

    Route::resource('database-backup', DatabaseBackupController::class)->middleware('role_or_permission:Super Admin|Admin');
    Route::get('database-backup/data/table', [DatabaseBackupController::class, 'datatable'])->middleware('role_or_permission:Super Admin|Admin');
    Route::get('database-backup/download/file/{id}', [DatabaseBackupController::class, 'downloadFile'])->name('db.download')->middleware('role_or_permission:Super Admin|Admin');

});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/CampaignController.php
<?php

namespace App\Http\Controllers;

use App\Events\BulkCampaignCreated;
use App\Events\SendBulkSMS;
use App\Models\Campaign;
use App\Models\CampaignContact;
use App\Models\CampaignGroup;
use App\Models\CampaignNumber;
use App\Models\Contact;
use App\Models\ContactGroup;
use App\Models\ScheduledCampaign;
use App\Models\SenderID;
use App\Traits\SMSPriceTrait;
use App\Traits\SMSTrait;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CampaignController extends Controller
{
    use SMSTrait;
    use SMSPriceTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Htctp\Response
     */
    public function index()
    {
        if (Auth::user()->isDemoUser()) {
            $sender_ids = SenderID::withoutGlobalScopes(['company'])->where('sender_id', '=', 'KentacyDEMO')->pluck('sender_id', 'id');
        } else {
            $sender_ids = SenderID::where('status', '=', 'active')->pluck('sender_id', 'id');
        }

        $business_id = Auth::user()->business_id;
        $contacts = Contact::whereBusinessId($business_id)->pluck('first_name', 'id');
        $groups = ContactGroup::whereBusinessId($business_id)->pluck('name', 'id');

        if (sizeof($contacts) > 1) {
            $contacts->prepend('ALL', 0);
        }
        if (sizeof($groups) > 1) {
            $groups->prepend('ALL', 0);
        }


        return view('sms.campaign', compact('sender_ids', 'contacts', 'groups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $name = $request->name;
        $numbers = $request->numbers;
        $contacts = $request->contacts;
        $groups = $request->groups;
        $is_schedule = $request->is_schedule;
        $schedule_time = $request->schedule_time;
        $sender_id = $request->sender_id;
        $message = $request->message;
        $business = Auth::user()->business;

        if ($is_schedule) {
            if (Carbon::parse($schedule_time)->format('Y-m-d H:i') <= Carbon::now()->format('Y-m-d H:i')) {
                return $this->sendError('Invalid Schedule Time');
            }
        }

        $campaign = new Campaign();
        $campaign->business_id = $business->id;
        $campaign->user_id = Auth::id();
        $campaign->name = $name;
        $campaign->sender_id = $sender_id;
        $campaign->type = 'campaign';
        $campaign->message = $message;
        $campaign->is_scheduled = !empty($is_schedule) ? 1 : 0;
        $campaign->scheduled_time = !empty($is_schedule) ? Carbon::parse($schedule_time)->format('Y-m-d H:i') : null;
        $campaign->status = !empty($is_schedule) ? 'pending' : 'running';
        $campaign->sms_count = 0;
        $campaign->page_count = $this->count($message)->messages;
        $campaign->cost_per_sms = $business->sms_charge;
        $campaign->start_balance = 0;
        $campaign->sms_charge = 0;
        $campaign->end_balance = 0;

        $campaign->save();


        if ($request->hasFile('file')) {
            $file = $request->file('file');
            $destinationPath = public_path() . '/campaign_numbers/';
            $fileName = 'campaign_numberList' . uniqid() . '.txt';
            $file->move($destinationPath, $fileName);

            $campaign->csv_file = $destinationPath . $fileName;

            $pdo = DB::connection()->getPdo();

            $pdo->beginTransaction();
            $path = str_replace('\\', '/', $destinationPath);


            $lines = file("$path$fileName");
            $line = $lines[0];
            switch (TRUE) {
                case substr($line, -2) === "\r\n" :
                    $query = "LOAD DATA LOCAL INFILE '$path$fileName' IGNORE INTO TABLE campaign_numbers FIELDS OPTIONALLY ENCLOSED BY '\"' TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES(@number) SET campaign_id =  $campaign->id , business_id =  $business->id ,csv_file='$fileName', number = TRIM(@number) ";
                    $pdo->exec($query);
                    break;
                case substr($line, -1) === "\n" :
                    $query = "LOAD DATA LOCAL INFILE '$path$fileName' IGNORE INTO TABLE campaign_numbers FIELDS OPTIONALLY ENCLOSED BY '\"' TERMINATED BY ',' LINES TERMINATED BY '
' IGNORE 1 LINES (@number) SET campaign_id =  $campaign->id , business_id =  $business->id ,csv_file='$fileName',number = TRIM(@number)";
                    $pdo->exec($query);
                    break;
                default :
                    $query = "LOAD DATA LOCAL INFILE '$path$fileName' IGNORE INTO TABLE campaign_numbers FIELDS OPTIONALLY ENCLOSED BY '\"' TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 LINES(@number) SET campaign_id =  $campaign->id , business_id =  $business->id ,csv_file='$fileName', number = TRIM(@number)";
                    $pdo->exec($query);
                    break;

            }

            $pdo->commit();
        }


        if (!empty($numbers)) {
            $numbers = collect(json_decode($numbers))->pluck('value');
            foreach ($numbers as $number) {
                $cn = CampaignNumber::firstOrCreate(['business_id' => $business->id, 'campaign_id' => $campaign->id, 'number' => $number]);
            }
        }

        if (!empty($contacts)) {
            $all_selected = collect($contacts)->contains(0);

            if ($all_selected) {
                $contacts = Contact::whereBusinessId($business->id)->get();
            } else {
                $contacts = Contact::whereIn('id', $contacts)->get();
            }


            foreach ($contacts as $number) {
                $contact = new CampaignContact();
                $contact->business_id = $business->id;
                $contact->campaign_id = $campaign->id;
                $contact->contact_id = $number->id;
                $contact->save();
                $cn = CampaignNumber::firstOrCreate(
                    ['business_id' => $business->id, 'campaign_id' => $campaign->id, 'number' => $number->number],
                    ['contact_id' => $number->id]);
            }
        }

        if (!empty($groups)) {

            $all_selected = collect($groups)->contains(0);
            if ($all_selected) {
                $groups = ContactGroup::whereBusinessId($business->id)->get();
            } else {
                $groups = ContactGroup::whereIn('id', $groups)->get();
            }


            foreach ($groups as $group) {
                foreach ($group->contacts as $number) {
                    $cn = CampaignNumber::firstOrCreate(
                        ['business_id' => $business->id, 'campaign_id' => $campaign->id, 'number' => $number->number],
                        ['contact_group_id' => $group->id]);
                }

                $cgroup = new CampaignGroup();
                $cgroup->business_id = $business->id;
                $cgroup->campaign_id = $campaign->id;
                $cgroup->contact_group_id = $group->id;
                $cgroup->save();
            }
        }

        $number_count = CampaignNumber::whereCampaignId($campaign->id)->count();
        $campaign->sms_count = $number_count;

        $charge = ($campaign->sms_count * $campaign->page_count) * $campaign->cost_per_sms;
        $real_cost = ($campaign->sms_count * $campaign->page_count) * 0.62;
        $profit = $charge - $real_cost;

        $campaign->profit = $profit;
        $campaign->sms_charge = $charge;
        $campaign->save();


        if ($this->hasActiveSubscription($business)) {
            $available_qty = $this->availableSMSQty($business);
            $campaign_sms_count = $campaign->sms_count * $campaign->page_count;
            if ($available_qty >= $campaign_sms_count) {
                if (!$campaign->is_scheduled) {
                    $created = BulkCampaignCreated::dispatch($campaign);
                } else {
                    $this->scheduleCampaign($campaign);
                }
            } else {
                return $this->sendError('Your Account Balance Is Insufficient . Please Top UP');
            }

        } elseif ($campaign->sms_charge < $business->balance) {
            $charge = ($campaign->sms_count * $campaign->page_count) * $campaign->cost_per_sms;
            $real_cost = ($campaign->sms_count * $campaign->page_count) * 0.62;
            $profit = $charge - $real_cost;

            $campaign->profit = $profit;
            $campaign->sms_charge = $charge;
            $campaign->save();
            if (!$campaign->is_scheduled) {
                $created = BulkCampaignCreated::dispatch($campaign);
            } else {
                $this->scheduleCampaign($campaign);
            }
        } else {
            $campaign->status = 'failed';
            $campaign->error_code = 'insufficient_balance';
            $campaign->save();
            return $this->sendError('Your Account Balance Is Insufficient . Please Top UP');
        }

        return $this->sendResponse($campaign, 'Message Sent Successfully');
    }

    function scheduleCampaign($campaign)
    {
        $sc = new ScheduledCampaign();
        $sc->campaign_id = $campaign->id;
        $sc->scheduled_at = Carbon::parse($campaign->scheduled_time)->format('Y-m-d H:i');
        $sc->save();
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Campaign $campaign
     * @return \Illuminate\Http\Response
     */
    public function show(Campaign $campaign, $id)
    {

        $campaignId = $id;

        $chartData = CampaignNumber::whereCampaignId($id)->get();

        $pendingCount = $chartData->where('sms_status', 'pending')->count();

resources/views/sms/campaign/campaing-numbers.blade.php
@extends('layouts.master')
@section('title','Campaign List')
@section('content')
    <div class="d-flex flex-column-fluid">
        <div class="container">

            <div class="card card-custom gutter-b mt-3" style="margin-top: 50px !important;">
                <div class="card-header flex-wrap py-3">
                    <div class="card-title">
                        <h3 class="card-label">Campaign Numbers List
                            <span
                                class="d-block text-muted pt-2 font-size-sm">{{env('APP_NAME')}} Campaign Number list</span>
                        </h3>
                    </div>
                    <div class="card-toolbar">

                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <table class="table table-bordered table-checkable" id="datatable">
                                <thead>
                                <tr>
                                    <th>Submitted AT</th>
                                    <th>Number</th>
                                    <th>Status</th>
                                    <th>Delivery Time</th>
                                    <th>Error Code</th>
                                </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-4">

                            <div id="chart_11" class="d-flex justify-content-center"
                                 style="min-height: 263.7px;margin-top: 75px">

                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </div>

    <div class="modal fade" id="filterModal" data-backdrop="static" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Filter</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {!! Form::open(['route' => 'contacts.store', 'method' => 'post','id'=>'filterForm', 'files' => true]) !!}
                <div class="modal-body">
                    @include('sms.campaign.filter')
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button onclick="filterForm('filterForm','filterModal')"
                            type="button" class="btn btn-success"><i class="fa fa-filter mr-1"></i> Filter
                    </button>
                </div>
                {!! Form::close() !!}

            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{asset('js/jquery.form.js')}}"></script>
    <script>
        DataTableOption.initDataTable('datatable', '/sms-campaigns-numbers/data/table/' +{{$campaignId}}, true, [0, 'desc']);

        function submitForm(form_id, modal_id, table_id) {
            validateFormNow(form_id).validate().then(function (status) {
                if (status == "Valid") {
                    form_id = '#' + form_id;
                    table_id = '#' + table_id;
                    let url = $(form_id).attr('action');
                    let method = $(form_id).attr('method');

                    $(form_id).ajaxSubmit(
                        {
                            clearForm: true,
                            url: url,
                            type: method,
                            success: function (result) {
                                ModalOptions.hideModal(modal_id);
                                if (result.success) {
                                    let table = $(table_id).DataTable();
                                    table.ajax.reload();
                                    Notifications.showSuccessMsg(result.message);
                                } else {
                                    Notifications.showErrorMsg(result.message);
                                }

                            },
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                ModalOptions.hideModal(modal_id);
                                Notifications.showErrorMsg(errorThrown);
                            }
                        }
                    );
                }
            });
        }

        function filterForm(form_id, modal_id) {
            let modal ='#'+modal_id;
            let status = $('#sms_status').val();
            let delivered_at = $('#delivered_at').val();
            let table = $('#datatable').DataTable();
            table.ajax.url('/sms-campaigns-numbers/data/table/+{{$campaignId}}?status=' + status + '&delivered_at=' + delivered_at + '&filter='+true).load();
            $(modal).modal('toggle');

        }

        $("#datatable_filter").append("<button class='btn btn-outline-primary ml-1 ' data-toggle='modal' data-target='#filterModal'> <i class='fa fa-filter'/> </button>")
    </script>

    <script>
        var options = {
            series: {{json_encode($chartDataArray)}},
            colors: ['#FFA800', '#B780FF', '#1BC5BD', '#F64E60'],
            labels: ['Pending', 'Sent', 'Delivered', 'Failed'],
            chart: {
                type: 'donut',
            },
            responsive: [{
                breakpoint: 480,
                options: {
                    chart: {
                        width: 200
                    },
                    legend: {
                        position: 'bottom'
                    },
                }
            }]
        };

        var chart = new ApexCharts(document.querySelector("#chart_11"), options);
        chart.render();
    </script>
@endpush

resources/views/sms/campaign/cfilter.blade.php
<div class="form-group row">
    <label class="col-form-label text-right col-lg-3 col-sm-12">Date Range</label>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="input-group">
            {!! Form::date('date_range', null, ['class' => 'form-control','placeholder'=>'','autocomplete'=>'off','id'=>'date_range']) !!}
        </div>
    </div>
</div>

<div class="form-group row">
    <label class="col-form-label text-right col-lg-3 col-sm-12">Status</label>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="input-group">
            {!! Form::select('sms_status',['pending'=>'Pending','sent'=>'Sent','delivered'=>'Delivered','failed'=>'Failed'],null, ['class' => 'form-control','placeholder'=>'','autocomplete'=>'off','id'=>'sms_status']) !!}
        </div>
    </div>
</div>

resources/views/sms/campaign/filter.blade.php
<div class="form-group row">
    <label class="col-form-label text-right col-lg-3 col-sm-12">Status</label>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="input-group">
            {!! Form::select('sms_status',['pending'=>'Pending','sent'=>'Sent','delivered'=>'Delivered','failed'=>'Failed'],null, ['class' => 'form-control','placeholder'=>'','autocomplete'=>'off','id'=>'sms_status']) !!}
        </div>
    </div>
</div>

<div class="form-group row">
    <label class="col-form-label text-right col-lg-3 col-sm-12">Delivered AT</label>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="input-group">
            {!! Form::date('delivered_at', null, ['class' => 'form-control','placeholder'=>'','autocomplete'=>'off','id'=>'delivered_at']) !!}
        </div>
    </div>
</div>

resources/views/sms/campaign/form.blade.php
<div class="form-group row">
    <label class="col-form-label text-right col-lg-3 col-sm-12">First Name</label>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="input-group">
            {!! Form::text('first_name', null, ['class' => 'form-control','placeholder'=>'Enter First Name','autocomplete'=>'off','id'=>'first_name','required']) !!}
        </div>
    </div>
</div>
<div class="form-group row">
    <label class="col-form-label text-right col-lg-3 col-sm-12">Last Name</label>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="input-group">
            {!! Form::text('last_name', null, ['class' => 'form-control','placeholder'=>'Enter Last Name','autocomplete'=>'off','id'=>'last_name']) !!}
        </div>
    </div>
</div>

<div class="form-group row">
    <label class="col-form-label text-right col-lg-3 col-sm-12">Number</label>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="input-group">
            {!! Form::number('number', null, ['class' => 'form-control','placeholder'=>'Enter Number','autocomplete'=>'off','id'=>'number','required']) !!}
        </div>
    </div>
</div>

<div class="form-group row">
    <label class="col-form-label text-right col-lg-3 col-sm-12">Birthday</label>
    <div class="col-lg-9 col-md-9 col-sm-12">
        <div class="input-group">
            {!! Form::date('birthday', null, ['class' => 'form-control','placeholder'=>'Enter Birthday','autocomplete'=>'off','id'=>'birthday']) !!}
        </div>
    </div>
</div>


{!! Form::hidden('business_id', Auth::user()->business->id) !!}

resources/views/sms/campaign/index.blade.php
@extends('layouts.master')
@section('title','Campaign List')
@section('content')
    <div class="d-flex flex-column-fluid">
        <div class="container">

            <div class="card card-custom gutter-b mt-3" style="margin-top: 50px !important;">
                <div class="card-header flex-wrap py-3">
                    <div class="card-title">
                        <h3 class="card-label">Campaign List
                            <span class="d-block text-muted pt-2 font-size-sm">{{env('APP_NAME')}} Campaign list</span>
                        </h3>
                    </div>
                    <div class="card-toolbar">
                        <a href="{{route('sms-campaigns.index')}}" class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Create New SMS Campaign">
                            <i class="fa fa-mail-bulk mr-1"></i> New SMS Campaign
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <table class="table table-bordered table-checkable" id="datatable">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>Campaign Name</th>
                            <th>Sender ID</th>
                            <th>Message Content</th>
                            <th>Campaign Status</th>
                            <th>Instant / Scheduled</th>
                            <th>Date & Time</th>
                            <th>Pages</th>
                            <th>Count</th>
                            <th>Charge</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

    <div class="modal fade" id="filterModal" data-backdrop="static" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Filter</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {!! Form::open(['route' => 'contacts.store', 'method' => 'post','id'=>'filterForm', 'files' => true]) !!}
                <div class="modal-body">
                    @include('sms.campaign.cfilter')
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button onclick="filterForm('filterForm','filterModal')"
                            type="button" class="btn btn-success"><i class="fa fa-filter mr-1"></i> Filter
                    </button>
                </div>
                {!! Form::close() !!}

            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{asset('js/jquery.form.js')}}"></script>
    <script>
        DataTableOption.initDataTable('datatable', '/sms-campaigns/data/table',true,[0,'desc']);

        function submitForm(form_id, modal_id, table_id) {
            validateFormNow(form_id).validate().then(function (status) {
                if (status == "Valid") {
                    form_id = '#' + form_id;
                    table_id = '#' + table_id;
                    let url = $(form_id).attr('action');
                    let method = $(form_id).attr('method');

                    $(form_id).ajaxSubmit(
                        {
                            clearForm: true,
                            url: url,
                            type: method,
                            success: function (result) {
                                ModalOptions.hideModal(modal_id);
                                if (result.success) {
                                    let table = $(table_id).DataTable();
                                    table.ajax.reload();
                                    Notifications.showSuccessMsg(result.message);
                                } else {
                                    Notifications.showErrorMsg(result.message);
                                }

                            },
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                ModalOptions.hideModal(modal_id);
                                Notifications.showErrorMsg(errorThrown);
                            }
                        }
                    );
                }
            });
        }

        function filterForm(form_id, modal_id) {
            let modal ='#'+modal_id;
            let status = $('#sms_status').val();
            let delivered_at = $('#delivered_at').val();

            let table = $('#datatable').DataTable();
            table.ajax.url('/sms-campaigns/data/table?status=' + status + '&delivered_at=' + delivered_at + '&filter='+true).load();
            $(modal).modal('toggle');

        }

        $("#datatable_filter").append("<button class='btn btn-outline-primary ml-1 ' data-toggle='modal' data-target='#filterModal'> <i class='fa fa-filter'/> </button>")


    </script>
@endpush